# Generated by Django 4.2.7 on 2023-12-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='json_data',
            field=models.JSONField(blank=True, db_column='json_data', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='devices_type',
            field=models.ForeignKey(blank=True, db_column='devices_type_id', help_text='Укажите тип устройства', null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_house.devicetype', verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='groups_id',
            field=models.ForeignKey(blank=True, db_column='groups_id', help_text='Укажите в какую группу входит устройство', null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_house.group', verbose_name='В какую группу входит устройство'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='air_temperature',
            field=models.PositiveSmallIntegerField(blank=True, db_column='air_temperature', help_text='Введите температуру воздуха', null=True, verbose_name='Температура воздуха'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='air_temperature_sensor',
            field=models.ForeignKey(blank=True, db_column='air_temperature_sensor_id', help_text='Выберите датчик температуры воздуха', null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_house.device', verbose_name='Датчик температуры воздуха'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='max_bar',
            field=models.PositiveSmallIntegerField(blank=True, db_column='max_bar', help_text='Введите значение давления при котором выключится устройство', null=True, verbose_name='Температура воздуха'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='min_bar',
            field=models.PositiveSmallIntegerField(blank=True, db_column='min_bar', help_text='Введите значение давления при котором включится устройство', null=True, verbose_name='Температура воздуха'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='socket_220',
            field=models.OneToOneField(blank=True, db_column='socket_220_id', help_text='Выберите розетку', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios_as_socket_220', to='smart_house.device', verbose_name='Розетка'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='water_leak_sensor_sensor',
            field=models.OneToOneField(blank=True, db_column='water_leak_sensor_id', help_text='Выберите датчик протечки воды', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios_as_water_leak_sensor_sensor', to='smart_house.device', verbose_name='Датчик протечки воды'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='water_pressure_sensor',
            field=models.OneToOneField(blank=True, db_column='water_pressure_sensor_id', help_text='Выберите датчик давления воды', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios_as_water_pressure_sensor', to='smart_house.device', verbose_name='Датчик давления воды'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='water_temperature',
            field=models.PositiveSmallIntegerField(blank=True, db_column='water_temperature', help_text='Введите температуру нагрева воды', null=True, verbose_name='Температура воды'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='water_temperature_sensor',
            field=models.OneToOneField(blank=True, db_column='water_temperature_sensor_id', help_text='Выберите датчик температуры воды', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios_as_water_temperature_sensor', to='smart_house.device', verbose_name='Датчик температуры воды'),
        ),
    ]
