# Generated by Django 4.2.7 on 2024-01-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_house', '0002_device_json_data_alter_device_devices_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', help_text='Введите вид сценария', max_length=50, verbose_name='Название вида сценария')),
            ],
            options={
                'db_table': 'scenario_type',
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='scenario_type',
            field=models.ForeignKey(blank=True, db_column='scenario_type_id', help_text='Укажите вид сценаярия', null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_house.scenariotype', verbose_name='Вид сценария'),
        ),
    ]
