# Generated by Django 4.2.7 on 2024-01-14 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_house', '0003_scenariotype_scenario_scenario_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='air_temperature',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='air_temperature_sensor',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='max_bar',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='min_bar',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='socket_220',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='water_leak_sensor_sensor',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='water_pressure_sensor',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='water_temperature',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='water_temperature_sensor',
        ),
        migrations.AddField(
            model_name='scenario',
            name='devices_id',
            field=models.ManyToManyField(to='smart_house.device'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(db_column='name', help_text='Введите название сценария', max_length=50, verbose_name='Название сценария'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_type',
            field=models.ForeignKey(db_column='scenario_type_id', help_text='Укажите вид сценаярия', null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_house.scenariotype', verbose_name='Вид сценария'),
        ),
    ]
